### ISSUE TITLE
Is this still supported?

### ISSUE THREAD

**Issue by jpruiz114** [CyberWarriors/Java-image-Comparison-Project#2]
Hi, I'm trying to compile this project. Is this a net beans project? I'm having some issues trying to compile it on Eclipse. Thanks.

**Comment by CyberWarriors** [comment]
Can u please give me a detailed information on what went wrong?

**Comment by jpruiz114** [comment]
I just was able to compile the project using NetBeans so I guess is solved now. Before I tried to use Eclipse. Thanks!
